import type { RoomieProfile } from './types';

// Источник фото — Unsplash (доступны без авторизации).
// Kept for local dev reference only — not exported from barrel; use GET /feed in production.
export const MOCK_PROFILES: RoomieProfile[] = [
  {
    id: 1,
    name: 'Алина',
    scenario: 'looking_housing_roomie',
    budgetMin: 40000,
    budgetMax: 55000,
    photos: ['https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=900&q=80'],
    vibeTags: [
      { id: 1, label: 'тишина' },
      { id: 2, label: 'без курения' },
      { id: 3, label: 'кот ок' },
    ],
    districts: [
      { id: 1, name: 'Хамовники' },
      { id: 2, name: 'Якиманка' },
    ],
    lifestyleScales: {
      noiseLevel: 0.2,
      cleanliness: 0.8,
      sleepSchedule: 0.7,
      socialLevel: 0.3,
      workFromHome: 0.9,
    },
    matchScore: 0.86,
    smokingOk: false,
    petsOk: true,
    smokes: false,
    hasPets: true,
    guestsPref: 'rarely',
    matchReasons: ['Оба предпочитают тишину дома', 'Схожий бюджет'],
  },
  {
    id: 2,
    name: 'Максим',
    scenario: 'has_housing_seeking_roomie',
    budgetMin: 50000,
    budgetMax: 70000,
    photos: ['https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=900&q=80'],
    vibeTags: [
      { id: 4, label: 'чистоплотный' },
      { id: 5, label: 'спорт' },
      { id: 6, label: 'без вечеринок' },
    ],
    districts: [{ id: 3, name: 'Басманный' }],
    lifestyleScales: {
      noiseLevel: 0.3,
      cleanliness: 0.9,
      sleepSchedule: 0.6,
      socialLevel: 0.4,
      workFromHome: 0.5,
    },
    matchScore: 0.78,
    smokingOk: false,
    petsOk: false,
    smokes: false,
    hasPets: false,
    guestsPref: 'sometimes',
    matchReasons: ['Высокая чистоплотность', 'Не курят'],
  },
  {
    id: 3,
    name: 'Дарья',
    scenario: 'looking_housing_roomie',
    budgetMin: 35000,
    budgetMax: 50000,
    photos: ['https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=900&q=80'],
    vibeTags: [
      { id: 7, label: 'студент' },
      { id: 8, label: 'без животных' },
      { id: 9, label: 'жаворонок' },
    ],
    districts: [
      { id: 4, name: 'Пресненский' },
      { id: 5, name: 'Тверской' },
    ],
    lifestyleScales: {
      noiseLevel: 0.4,
      cleanliness: 0.7,
      sleepSchedule: 0.8,
      socialLevel: 0.5,
      workFromHome: 0.3,
    },
    matchScore: 0.71,
    smokingOk: false,
    petsOk: false,
    smokes: false,
    hasPets: false,
    guestsPref: 'rarely',
    matchReasons: ['Ранний подъём', 'Предпочитают тишину'],
  },
  {
    id: 4,
    name: 'Игорь',
    scenario: 'has_housing_seeking_roomie',
    budgetMin: 60000,
    budgetMax: 80000,
    photos: ['https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=900&q=80'],
    vibeTags: [
      { id: 10, label: 'творчество' },
      { id: 11, label: 'сова' },
      { id: 12, label: 'гости иногда' },
    ],
    districts: [{ id: 6, name: 'Мещанский' }],
    lifestyleScales: {
      noiseLevel: 0.7,
      cleanliness: 0.5,
      sleepSchedule: 0.2,
      socialLevel: 0.7,
      workFromHome: 0.4,
    },
    matchScore: 0.65,
    smokingOk: true,
    petsOk: true,
    smokes: true,
    hasPets: true,
    guestsPref: 'often',
    matchReasons: ['Творческая атмосфера'],
    matchRisks: ['Разные режимы дня'],
  },
  {
    id: 5,
    name: 'Полина',
    scenario: 'looking_housing_roomie',
    budgetMin: 45000,
    budgetMax: 60000,
    photos: ['https://images.unsplash.com/photo-1517841905240-472988babdf9?w=900&q=80'],
    vibeTags: [
      { id: 13, label: 'веган' },
      { id: 14, label: 'чистота' },
      { id: 1, label: 'тишина' },
    ],
    districts: [
      { id: 7, name: 'Арбат' },
      { id: 1, name: 'Хамовники' },
    ],
    lifestyleScales: {
      noiseLevel: 0.1,
      cleanliness: 1.0,
      sleepSchedule: 0.7,
      socialLevel: 0.2,
      workFromHome: 0.6,
    },
    matchScore: 0.89,
    smokingOk: false,
    petsOk: false,
    smokes: false,
    hasPets: false,
    guestsPref: 'rarely',
    matchReasons: ['Максимальная чистоплотность', 'Тихий режим', 'Схожий бюджет'],
  },
  {
    id: 6,
    name: 'Артём',
    scenario: 'has_housing_seeking_roomie',
    budgetMin: 40000,
    budgetMax: 55000,
    photos: ['https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=900&q=80'],
    vibeTags: [
      { id: 4, label: 'чистоплотный' },
      { id: 3, label: 'кот ок' },
      { id: 1, label: 'тишина' },
    ],
    districts: [
      { id: 8, name: 'Останкинский' },
      { id: 9, name: 'Алексеевский' },
    ],
    lifestyleScales: {
      noiseLevel: 0.3,
      cleanliness: 0.8,
      sleepSchedule: 0.6,
      socialLevel: 0.4,
      workFromHome: 0.8,
    },
    matchScore: 0.82,
    smokingOk: false,
    petsOk: true,
    smokes: false,
    hasPets: true,
    guestsPref: 'sometimes',
    matchReasons: ['Кот приветствуется', 'Работают из дома'],
  },
];
